SELECT * FROM EMPREGADO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM CLIENTE;

SELECT PRIM_NOME, SALARIO, CARGO 
FROM EMPREGADO;

SELECT PRIM_NOME, SALARIO, CARGO 
FROM EMPREGADO
WHERE SALARIO > 6500;

SELECT PRIM_NOME, SALARIO, CARGO 
FROM EMPREGADO
WHERE SALARIO < 10000 OR UPPER(CARGO) = 'PRESIDENTE';

SELECT * FROM EMPREGADO
WHERE DT_ADMISSAO BETWEEN '01-01-2008' AND '31-12-2008';

SELECT * FROM EMPREGADO
WHERE PRIM_NOME LIKE '______%';

/*Juncoes*/

/*Juncao Crusadas*/
SELECT * FROM EMPREGADO CROSS JOIN DEPARTAMENTO;

/*Juncao Interior*/

SELECT * FROM EMPREGADO INNER JOIN DEPARTAMENTO 
ON ID_DEPTO = DEPARTAMENTO.ID;

/*ID_EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO*/
/*ALIAS DE TABELAS*/

SELECT E.ID, E.ULT_NOME AS "SOBRENOME", E.PRIM_NOME AS "NOME", E.SALARIO, D.NOME AS "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID;

SELECT EMP.ID, EMP.ULT_NOME AS "SOBRENOME", EMP.PRIM_NOME AS "NOME", EMP.SALARIO, DEP.NOME AS "DEPARTAMENTO"
FROM EMPREGADO EMP INNER JOIN DEPARTAMENTO DEP
ON EMP.ID_DEPTO = DEP.ID
WHERE UPPER(DEP.NOME) = 'VENDAS';


/*ID_EMPREGADO, ULT_NOME, PRIM_NOME, SALARIO E O NOME DO DEPARTAMENTO EMPREGADO COM SALARIO > 7500
E QUE NÃO TRABALHAM EM VENDAS*/
SELECT EMP.ID, EMP.ULT_NOME AS "SOBRENOME", EMP.PRIM_NOME AS "NOME", EMP.SALARIO, DEP.NOME AS "DEPARTAMENTO"
FROM EMPREGADO EMP INNER JOIN DEPARTAMENTO DEP
ON EMP.ID_DEPTO = DEP.ID
WHERE EMP.SALARIO > 7500 AND UPPER(DEP.NOME) != 'VENDAS';


SELECT EMP.ID, EMP.ULT_NOME AS "SOBRENOME", EMP.PRIM_NOME AS "NOME", EMP.SALARIO, DEP.NOME AS "DEPARTAMENTO"
FROM EMPREGADO EMP INNER JOIN DEPARTAMENTO DEP
ON EMP.ID_DEPTO = DEP.ID
WHERE EMP.SALARIO = 8000 OR SALARIO = 18000 AND UPPER(DEP.NOME) = 'VENDAS';

SELECT EMP.ID, EMP.ULT_NOME AS "SOBRENOME", EMP.PRIM_NOME AS "NOME", EMP.SALARIO, DEP.NOME AS "DEPARTAMENTO"
FROM EMPREGADO EMP INNER JOIN DEPARTAMENTO DEP
ON EMP.ID_DEPTO = DEP.ID
WHERE UPPER(DEP.NOME) = 'VENDAS' AND (EMP.SALARIO = 8000 OR EMP.SALARIO = 18000);

/*Juncao com mais de duas tabelas*/
/*NOME DO CLIENTE, NOME DO EMPREGADO, CARGO DO EMPREGADO, NOME DO DEPARTAMENTO*/

SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO", D.NOME "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
INNER JOIN CLIENTE C
ON C.VENDEDOR = E.ID;


SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO", D.NOME "DEPARTAMENTO"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
INNER JOIN CLIENTE C
ON C.VENDEDOR = E.ID
WHERE UPPER(E.PRIM_NOME) = 'ALBERTO';



/*Juncao Exterior*/
/*EXIBIR CLIENTE, NOME DO EMPREGADO E O CARGO*/

-- LEFT
-- RIGHT

SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E RIGHT JOIN CLIENTE C ON C.VENDEDOR = E.ID;

SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E RIGHT JOIN CLIENTE C ON C.VENDEDOR = E.ID
WHERE E.PRIM_NOME IS NULL;

SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E LEFT JOIN CLIENTE C ON C.VENDEDOR = E.ID;

SELECT E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E LEFT JOIN CLIENTE C ON C.VENDEDOR = E.ID
WHERE C.NOME IS NULL;

-- UNION
SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E RIGHT JOIN CLIENTE C ON C.VENDEDOR = E.ID
UNION
SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", C.NOME
FROM EMPREGADO E LEFT JOIN CLIENTE C ON C.VENDEDOR = E.ID;

-- INTERSEÇÃO
SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E RIGHT JOIN CLIENTE C ON C.VENDEDOR = E.ID
INTERSECT
SELECT C.NOME "CLIENTE", E.PRIM_NOME "VENDEDOR", E.CARGO "CARGO"
FROM EMPREGADO E LEFT JOIN CLIENTE C ON C.VENDEDOR = E.ID;


/***FUNCOES DE GRUPO***/

-- AVG ==> MEDIA
-- SUM ==> SOMA
-- MAX ==> MAIOR VALOR
-- MIN ==> MENOR VALOR
-- COUNT ==> CONTA OS REGISTROS

SELECT * FROM EMPREGADO;

-- AVG E SUM APENAS VALORES NUMERICOS
SELECT TO_CHAR(AVG(SALARIO), 'R$ 99999.99') FROM EMPREGADO;
SELECT SUM(SALARIO) FROM EMPREGADO;


SELECT MAX(SALARIO) FROM EMPREGADO;
SELECT MAX(DT_ADMISSAO) FROM EMPREGADO;
SELECT MAX(PRIM_NOME) FROM EMPREGADO;

SELECT MIN(SALARIO) FROM EMPREGADO;
SELECT MIN(DT_ADMISSAO) FROM EMPREGADO;
SELECT MIN(PRIM_NOME) FROM EMPREGADO;

SELECT COUNT(ID) FROM EMPREGADO;
SELECT COUNT(ID_GERENTE) FROM EMPREGADO;
SELECT COUNT(*) FROM EMPREGADO;


/*A MEDIA SALARIAL DOS DEPARTAMENTOS*/
SELECT ID_DEPTO, TO_CHAR(AVG(SALARIO), 'R$ 99999.99') FROM EMPREGADO 
GROUP BY ID_DEPTO;

SELECT ID_DEPTO, COUNT(*) FROM EMPREGADO
GROUP BY ID_DEPTO;

SELECT CARGO, COUNT(*) FROM EMPREGADO
GROUP BY CARGO;


/*LISTAR A QUANTIDADE DE EMPREGADOS, SALARIO MEDIO E SOMA DOS SALARIOS DOS 
* EMPREGADOS DE CADA DEPARTAMENTO E DENTRO DO DEPARTAMENTO PARA CADA CARGO */

SELECT ID_DEPTO, CARGO, COUNT(*), AVG(SALARIO) FROM EMPREGADO
GROUP BY ID_DEPTO, CARGO;

/*LISTAR A QUANTIDADE DE EMPREGADOS, SALARIO MEDIO E SOMA DOS SALARIOS DOS 
* EMPREGADOS DE CADA DEPARTAMENTO E DENTRO DO DEPARTAMENTO PARA CADA CARGO 
* APENAS DOS DEPARTAMENTOS COM MEDIA SALARIAL ACIMA DE 10K
*/

SELECT ID_DEPTO, CARGO, COUNT(*), AVG(SALARIO) FROM EMPREGADO
GROUP BY ID_DEPTO, CARGO
HAVING AVG(SALARIO) > 10000;

/*
SELECT [COLUNAS]
FROM [TABELAS]
[JOINS] ON [CLAUSULA DE JUNCAO]
WHERE [FILTROS]
GROUP BY [COLUNAS]
HAVING [FILTROS DE GRUPO]
ORDER BY [COLUNAS];
*/

/*NOME DO DEPARTAMENTO, CARGO, QUANTIDADE EMPREGADOS, MEDIA SALARIAL, SOMA SALARIOS*/

SELECT D.NOME, E.CARGO, COUNT(*), TO_CHAR(AVG(SALARIO), 'R$ 99999.99') AS "MEDIA", SUM(E.SALARIO) AS "SOMA"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE UPPER(CARGO) LIKE 'DIRETOR%'
GROUP BY D.NOME, E.CARGO
HAVING AVG(SALARIO) > 19000
ORDER BY AVG(SALARIO) DESC;

/*Subqueries (SUBCONSULTAS)*/

SELECT E.PRIM_NOME, E.SALARIO, E.CARGO FROM EMPREGADO E INNER JOIN DEPARTAMENTO D
ON E.ID_DEPTO = D.ID
WHERE UPPER(D.NOME) = 'VENDAS';

SELECT PRIM_NOME, SALARIO, CARGO FROM EMPREGADO
WHERE ID_DEPTO = 20;

SELECT ID FROM DEPARTAMENTO
WHERE UPPER(NOME) = 'VENDAS';

SELECT PRIM_NOME, SALARIO, CARGO FROM EMPREGADO
WHERE ID_DEPTO = (SELECT ID FROM DEPARTAMENTO WHERE UPPER(NOME) = 'VENDAS');
